# Generated by Django 4.2.5 on 2023-10-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptechNewApp', '0009_inquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('business', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('service', models.CharField(choices=[('Web Application', 'Web Application'), ('Mobile Application', 'Mobile Application'), ('Expert Website Design', 'Exper Website Design'), ('Tech Consultancy', 'Tech Consultancy'), ('Data Transcription', 'Data Transcriptions'), ('Research Questionnaire Design', 'Research Questionnaire Design'), ('Data Entry', 'Data Entry')], max_length=100)),
            ],
        ),
    ]
