# Generated by Django 4.2.5 on 2023-10-10 18:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deptechNewApp', '0011_alter_post_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
