# Generated by Django 4.2.5 on 2023-10-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptechNewApp', '0013_alter_inquery_email_alter_inquery_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquery',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inquery',
            name='subject',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
