# Generated by Django 4.2.5 on 2023-10-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptechNewApp', '0015_alter_inquery_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterField(
            model_name='inquery',
            name='contact',
            field=models.IntegerField(blank=True, default=8888, null=True),
        ),
        migrations.AlterField(
            model_name='inquery',
            name='email',
            field=models.EmailField(default='tarnue@gmail.com', max_length=200),
        ),
        migrations.AlterField(
            model_name='inquery',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inquery',
            name='subject',
            field=models.CharField(default='urgent', max_length=300),
        ),
    ]
