# Generated by Django 4.2.5 on 2023-10-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deptechNewApp', '0016_alter_post_options_alter_inquery_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='click on the link above to read in more detail', max_length=2000),
        ),
    ]
