# Generated by Django 4.2.5 on 2024-04-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deptechNewApp", "0017_post_snippet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="address",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="booking",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
